source/SocialGoal/ViewModels/CommentsViewModel.cs
using System;
using SocialGoal.Model.Models;

namespace SocialGoal.Web.ViewModels
{
    public class CommentsViewModel
    {
        public int CommentId { get; set; }

        public string CommentText { get; set; }

        public int UpdateId { get; set; }

        public string UserId { get; set; }

        public DateTime CommentDate { get; set; }

        public ApplicationUser User { get; set; }
    }
}

source/SocialGoal/ViewModels/GoalViewModel.cs
using System;
using System.Collections.Generic;
using SocialGoal.Model.Models;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace SocialGoal.Web.ViewModels
{
    public class GoalViewModel
    {
        public int GoalId { get; set; }

        public string GoalName { set; get; }

        public string Desc { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd MMM yyyy}")]
        public DateTime StartDate { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd MMM yyyy}")]
        public DateTime EndDate { get; set; }

        public double? Target { get; set; }

        public bool GoalType { get; set; }

        public int MetricId { get; set; }

        public int GoalStatusId { get; set; }

        public string UserId { get; set; }

        public Metric Metric { get; set; }

        public IEnumerable<SelectListItem> GoalStatuses { get; set; }

        public GoalStatus GoalStatus { get; set; }

        public ApplicationUser User { get; set; }

        public DateTime CreatedDate { get; set; }

        public bool? Supported { get; set; }

      //  public int? GroupGoalId { get; set; }

        public int? GroupId { get; set; }

        public virtual IEnumerable<Support> Supports { get; set; }

        public virtual IEnumerable<Update> Updates { get; set; }

    }
}

source/SocialGoal/ViewModels/UpdateViewModel.cs
using System;
using System.Collections.Generic;
using SocialGoal.Model.Models;
using System.Linq;
using System.Web;

namespace SocialGoal.Web.ViewModels
{
    public class UpdateViewModel
    {
        public int UpdateId { get; set; }

        public string Updatemsg { get; set; }

        public double? status { get; set; }

        public int GoalId { get; set; }

        public DateTime UpdateDate { get; set; }

        public virtual Goal Goal { get; set; }

        public virtual ICollection<Comment> Comments { get; set; }

        public bool? IsSupported { get; set; }

        public virtual ICollection<UpdateSupport> UpdateSupports { get; set; }
    }
}

source/SocialGoal/Controllers/GoalController.cs
using AutoMapper;
using SocialGoal.Model.Models;
using SocialGoal.Service;
using SocialGoal.Web.Core.Models;
using SocialGoal.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SocialGoal.Web.Core.Extensions;
using SocialGoal.Web.Mailers;
using SocialGoal.Properties;
using Microsoft.AspNet.Identity;

namespace SocialGoal.Web.Controllers
{
    [Authorize]
    public class GoalController : Controller
    {
        private readonly IGoalService goalService;
        private readonly IMetricService metricService;
        private readonly IFocusService focusService;
        private readonly ISupportService supportService;
        private readonly IUpdateService updateService;
        private readonly ICommentService commentService;
        private readonly IUserService userService;
        public readonly ISecurityTokenService securityTokenService;
        public readonly ISupportInvitationService supportInvitationService;
        private readonly IGoalStatusService goalStatusService;
        private readonly ICommentUserService commentUserService;
        private readonly IUpdateSupportService updateSupportService;

        private IUserMailer userMailer = new UserMailer();
        public IUserMailer UserMailer
        {
            get { return userMailer; }
            set { userMailer = value; }
        }

        public GoalController(IGoalService goalService, IMetricService metricService, IFocusService focusService, ISupportService supportService, IUpdateService updateService, ICommentService commentService, IUserService userService, ISecurityTokenService securityTokenService, ISupportInvitationService supportInvitationService, IGoalStatusService goalStatusService, ICommentUserService commentUserService, IUpdateSupportService updateSupportService)
        {
            this.goalService = goalService;
            this.supportInvitationService = supportInvitationService;
            this.metricService = metricService;
            this.focusService = focusService;
            this.supportService = supportService;
            this.updateService = updateService;
            this.commentService = commentService;
            this.userService = userService;
            this.securityTokenService = securityTokenService;
            this.goalStatusService = goalStatusService;
            this.commentUserService = commentUserService;
            this.updateSupportService = updateSupportService;
        }

        public ActionResult Index(int id)
        {
            var goal = goalService.GetGoal(id);
            if (goal == null)
            {
                return HttpNotFound();
            }
            var goalDetails = Mapper.Map<Goal, GoalViewModel>(goal);
            goalDetails.Supported = supportService.IsGoalSupported(id, User.Identity.GetUserId());
            var goalstatus = goalStatusService.GetGoalStatus();
            goalDetails.GoalStatuses = goalstatus.ToSelectListItems(goal.GoalStatusId);
            return View(goalDetails);
        }

        public ViewResult MyGoal()
        {
            string userid = User.Identity.GetUserId();
            var Goals = goalService.GetMyGoals(userid);
            var goalDetails = Mapper.Map<IEnumerable<Goal>, IEnumerable<GoalViewModel>>(Goals);
            return View(goalDetails);
        }

        public ViewResult FollowedGoal()
        {
            var followed = supportService.GetUserSupportedGoals(User.Identity.GetUserId(), goalService);
            return View(followed);
        }

        public PartialViewResult Create()
        {
            var createGoal = new GoalFormModel();
            var metrics = metricService.GetMetrics();
            var goalstatus = goalStatusService.GetGoalStatus();
            createGoal.Metrics = metrics.ToSelectListItems(-1);
            return PartialView(createGoal);
        }

        [HttpPost]
        public ActionResult Create(GoalFormModel createGoal)
        {
            Goal goal = Mapper.Map<GoalFormModel, Goal>(createGoal);
            var errors = goalService.CanAddGoal(goal, updateService).ToList();
            ModelState.AddModelErrors(errors);
            if (ModelState.IsValid)
            {
                goalService.CreateGoal(goal);
                return RedirectToAction("Index", new { id = goal.GoalId });
            }
            var metrics = metricService.GetMetrics();
            var goalstatuss = goalStatusService.GetGoalStatus();
            createGoal.Metrics = metrics.ToSelectListItems(-1);
            return View("Create", createGoal);
        }

        public ActionResult Edit(int id)
        {
            var goal = goalService.GetGoal(id);
            GoalFormModel editGoal = Mapper.Map<Goal, GoalFormModel>(goal);
            if (goal == null)
            {
                return HttpNotFound();
            }
            var metrics = metricService.GetMetrics();
            if (goal.Metric != null)
                editGoal.Metrics = metrics.ToSelectListItems(goal.Metric.MetricId);
            else
                editGoal.Metrics = metrics.ToSelectListItems(-1);
            return View(editGoal);
        }

        [HttpPost]
        public ActionResult Edit(GoalFormModel editGoal)
        {
            Goal goalToEdit = Mapper.Map<GoalFormModel, Goal>(editGoal);
            var errors = goalService.CanAddGoal(goalToEdit, updateService);
            ModelState.AddModelErrors(errors);
            if (ModelState.IsValid)
            {
                goalService.EditGoal(goalToEdit);
                return RedirectToAction("Index", new { id = editGoal.GoalId });
            }
            else
            {
                var metrics = metricService.GetMetrics();
                var goalstatus = goalStatusService.GetGoalStatus();
                var goal = goalService.GetGoal(editGoal.GoalId);
                if (goal.Metric != null)
                    editGoal.Metrics = metrics.ToSelectListItems(goal.Metric.MetricId);
                else
                    editGoal.Metrics = metrics.ToSelectListItems(-1);

                return View(editGoal);
            }
        }

        [HttpPost]
        public string GoalStatus(int id, int goalid)
        {
            var goal = goalService.GetGoal(goalid);
            goal.GoalStatusId = id;
            goalService.SaveGoal();
            string msg = goal.GoalStatus.GoalStatusType;
            return msg;
        }

        public ActionResult Delete(int id)
        {
            var goal = goalService.GetGoal(id);
            if (goal == null)
            {
                return HttpNotFound();
            }
            return View(goal);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var goal = goalService.GetGoal(id);
            if (goal == null)
            {
                return HttpNotFound();
            }

            goalService.DeleteGoal(id);
            return RedirectToAction("Index", "Home");
        }

        public PartialViewResult MyGoals()
        {
            string userid = User.Identity.GetUserId();
            var Goals = goalService.GetMyGoals(userid);
            return PartialView("_MyGoalsView", Goals);
        }

        public PartialViewResult GoalsFollowing()
        {
            var followed = supportService.GetUserSupportedGoals(User.Identity.GetUserId(), goalService);
            return PartialView("_FollowedGoals", followed);
        }

        public PartialViewResult DisplayUpdates(int id)
        {
            var Updates = Mapper.Map<IEnumerable<Update>, IEnumerable<UpdateViewModel>>(updateService.GetUpdatesByGoal(id));
            foreach (var item in Updates)
            {
                item.IsSupported = updateSupportService.IsUpdateSupported(item.UpdateId, User.Identity.GetUserId());
            }
            UpdateListViewModel updates = new UpdateListViewModel()
            {

                Updates = Updates,
                Metric = goalService.GetGoal(id).Metric,
                Target = goalService.GetGoal(id).Target,
                // IsSupported =  updateSupportService.IsUpdateSupported(,((SocialGoalUser)(User.Identity)).UserId)
            };
            return PartialView("_UpdateView", updates);
        }

        public ViewResult Supporters(int id)
        {
            var members = supportService.GetSupportersOfGoal(id, userService);
            GoalSupporterViewModel gsvm = new GoalSupporterViewModel() { GoalId = id, Goal = goalService.GetGoal(id), Users = members };
            return View(gsvm);
        }

        [HttpPost]
        public ActionResult SaveUpdate(UpdateFormModel newupdate)
        {
            // Update update = Mapper.Map<UpdateFormModel, Update>(newupdate);
            if (ModelState.IsValid)
            {
                Update update = Mapper.Map<UpdateFormModel, Update>(newupdate);
                update.Goal = goalService.GetGoal(newupdate.GoalId);
                var updateVal = updateService.GetHighestUpdateValue(newupdate.GoalId);
               
                if(updateVal!=null)
                {  
                    if (updateVal.status <= newupdate.status)
                    {
                        updateService.CreateUpdate(update);
                       
                    }
                    else
                    {
                        update.status = -1;
                        ModelState.AddModelError(update.Updatemsg, "cannot enter");
                    }
                }
                else
                {
                    updateService.CreateUpdate(update);
                }


                     var Updates = Mapper.Map<IEnumerable<Update>, IEnumerable<UpdateViewModel>>(updateService.GetUpdatesByGoal(newupdate.GoalId));
                     foreach (var item in Updates)
                     {

source/SocialGoal/Views/Goal/Create.cshtml
@using Microsoft.AspNet.Identity
@model SocialGoal.Web.ViewModels.GoalFormModel
@{
    ViewBag.Title = "Home Page";
        //Layout = "~/Views/Shared/_HomeLayout.cshtml";

}
<div>
<div class="span5">
    @using (Html.BeginForm("Create", "Goal", FormMethod.Post, new { @id = "form" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        <fieldset>
        <legend></legend>
            <table>
                <tr>
                
                    <td>
                        @Html.TextBoxFor(model => model.GoalName, new { @class = "span3", style = "display:block;width:270px;;float:left", placeholder = "Enter the goal name" })<br>
                        @Html.ValidationMessageFor(model => model.GoalName)
                    </td>
                </tr>
                <tr>
                
                    <td class="editor-field">
                        @Html.TextAreaFor(model => model.Desc, new { @class = "span3", placeholder = "Enter the description", style = "display:block;width:270px;;float:left" })
                        @Html.ValidationMessageFor(model => model.Desc)
                    </td>
                </tr>
                <tr>
                  
                    <td>
                        @Html.TextBoxFor(model => model.StartDate, new { @class = "ui-datepicker span3", @style = "display:block;width:270px;;float:left", placeholder = "Enter the start date", @readonly = "readonly" })
                        @Html.ValidationMessageFor(model => model.StartDate)
                    </td>
                </tr>
                <tr>
                   
                    <td >
                        @Html.TextBoxFor(model => model.EndDate, new { @class = "ui-datepicker span3", @style = "display:block;width:270px;;float:left", placeholder = "Enter the end date", @readonly = "readonly" })
                        @Html.ValidationMessageFor(model => model.EndDate)
                    </td>
                </tr>
                <tr>
                  
                    <td>
                 
                        @Html.DropDownListFor(model => model.MetricId, Model.Metrics, "--Select Metric--", new { @class = "span4", @style = "display:block;width:270px;;float:left" })
                        @Html.ValidationMessageFor(model => model.MetricId)
                    </td>
                </tr>
                <tr>
                  
                    <td>
                        @Html.TextBoxFor(model => model.Target, new { @class = "span3", id = "Target",  placeholder = "Enter the target to be achieved", style = "width: 270px;" })
                        <a href="#"  id="targetinfo" rel ="popover" data-content= "Fix the target of the goal based on metric selected" data-trigger ="hover" data-placement="top" data-originals-title ="Target"><i class="icon-info-sign"></i> </a>
                      <div id="NumberValidation"></div>
                    </td>
                </tr>
                <tr>
                    <td>@Html.CheckBoxFor(model => model.GoalType, true)&nbsp;&nbsp;Make this goal as private</td>
                </tr>
                <tr><td height="20"></td></tr>
                <tr>
                    <td>
                    <button id="submitbtn" class="btn btn-primary" value="Submit"> Create</button>&nbsp;&nbsp;
                    <button class="btn" type ="reset" value="Cancel" onclick="window.location.href='@Url.Action("Index", "Home")'">Cancel</button>                        
                    </td>
                </tr>

               
                @Html.Hidden("UserId", User.Identity.GetUserId())
                
            </table>
            
        </fieldset>
    }
</div>
</div>
<script type="text/javascript">


    $(document).ready(function () {

        $('.ui-datepicker').each(function (i, v) {
            $(v).datepicker({
                dateFormat: 'dd-M-yy',
                buttonImage: '@Url.Content("~/Content/calendar.gif")',
                buttonImageOnly: true,
                showOn: "button"
            });

        });

        $('#form').submit(function(e)  {
            var target = $('#Target').val();
            if (target != '') {
                if (DecimalValidate(target)) {
                    $('#NumberValidation').html('');
                    return true;
                }
                else {
                    $('#NumberValidation').html('<label class="field-validation-error">Please enter valid status</label>');
                    e.preventDefault();
                    return false;
                }
            }

        });

    });

    $("#Description").focus(function () {
        $(this).animate({ "height": "60px" }, "slow");
        return false;
    });
    $("#Description").blur(function () {
        $("#Description").animate({ "height": "22px" }, "slow");
        return false;
    });

    $(function () {
        $("#targetinfo").popover();
    });


    function DecimalValidate(num) {
        var regex = /^[-+]?[0-9]+(\.[0-9]+)?$/;
        if (regex.test(num)) {
            return true;
        } else {
            return false;
        }
    }


</script>

source/SocialGoal/Views/Goal/Delete.cshtml
@model SocialGoal.Model.Models.Goal
@{
    ViewBag.Title = "Delete Goal";
}
@*<div class="alert fade in">
<button type ="button" class ="close" data-dismiss ="alert" >×</button>
            <strong class="alert-heading">
                Warning!</strong>
            Best check your self, before deleting
        </div>*@
<div class="alert alert-block alert-error fade in">
    <strong>
        Delete</strong>
  <br />
        Are you sure you want to delete this?
<br />
<br />


    <strong >@Html.DisplayFor(model => model.GoalName)</strong>
    <table>
        <tr >
            <td class="display-label">
                @Html.DisplayNameFor(model => model.GoalName)
            </td>
            <td class="display-field">
            &nbsp;&nbsp;&nbsp;
                @Html.DisplayFor(model => model.GoalName)
            </td>
        </tr>
        <tr>
            <td class="display-label">
                @Html.DisplayNameFor(model => model.Desc)
            </td>
            <td class="display-field">
             &nbsp;&nbsp;&nbsp;
                @Html.DisplayFor(model => model.Desc)
            </td>
        </tr>
        <tr>
            <td class="display-label">
                @Html.DisplayNameFor(model => model.StartDate)
            </td>
            <td class="display-field">
             &nbsp;&nbsp;&nbsp;
                @Html.DisplayFor(model => model.StartDate)
            </td>
        </tr>
        <tr>
            <td class="display-label">
                @Html.DisplayNameFor(model => model.EndDate)
            </td>
            <td class="display-field">
             &nbsp;&nbsp;&nbsp;
                @Html.DisplayFor(model => model.EndDate)
            </td>
            <td>@Html.HiddenFor(mbox => mbox.GoalId)
            </td>
        </tr>
    </table>
    <br />
    <div id="divDelete@(Model.GoalId)">
    </div>
    @using (Html.BeginForm())
    {
        <p>
            <button class="btn btn-danger" type="submit" value="Submit">
                Delete</button>
                 <button class="btn" type="reset" value="Cancel" onclick="window.location.href='@Url.Action("Index", "Goal", new { id = @Model.GoalId })'">
        Cancel</button>
        </p>
      
        
    }
   
</div>

source/SocialGoal/Views/Goal/FollowedGoal.cshtml
@model IEnumerable<SocialGoal.Model.Models.Goal>
@{
    ViewBag.Title = "MyGoals";
    Layout = "~/Views/Shared/_PageLayout.cshtml";
}
@if (Model.Count() == 0)
{
   <div class ="alert alert-info">
   No results To Display
   </div>
}

@foreach (var item in Model)
{ 
    <div class="span2 alert alert-info">
        <div>
            @Html.ActionLink(@item.GoalName + " - " + @item.Supports.Count() + " Follower(s)", "Index", "Goal", new { id = @item.GoalId }, null) </div>
        <b>@Html.ActionLink(item.User.UserName, "UserProfile", "Account", new { id = item.UserId }, null)</b>
    </div>
}

source/SocialGoal/Views/Goal/InviteUser.cshtml
@model SocialGoal.Model.Models.ApplicationUser
<div class="alert"> @Model.UserName has been invited to follow the goal.</div>

source/SocialGoal/Views/Goal/ListOfGoals.cshtml
@model SocialGoal.Web.ViewModels.GoalsPageViewModel
@{
    ViewBag.Title = "ListOfGoals";
}
@*<script src="/Scripts/handlebars-1.0.rc.1.js" type="text/javascript"></script>*@


<div class="well span12">
<div class="span4" style="padding-left:30px;"><h4>Goals</h4></div>
<div  class="span8">
    <strong>Sort By</strong>
    @Html.DropDownList("sortby", Model.SortBy, new { @onchange = "ListOfGoals();" })
    <strong>Filter By</strong>
    @Html.DropDownList("filterby", Model.FilterBy, new { @onchange = "ListOfGoals();" })
</div>

<div id ="listofgoals" style="float:left;" class="span11">
     
    @if (Model.GoalList.Count() == 0)
    {
        <div class="alert alert-info">
            No results found
        </div>
    }
    else
    {       
        <div class="span12" id="goalListContainer" style="margin-top:10px;">
       <hr />
          <table class="table">
        @Html.Partial("_Goalslist",Model.GoalList)
       </table>
        </div>
        if (Model.GoalList.Count() == 5)
        {
         <div  id="morelink"> <a href="#" onclick="loadMore();">More Goals</a></div>
        }
    }
</div>
</div>
     <div id="content" style="color:Red;"></div>
      <div class="hiddenData" style="display:none;"></div>
<script type="text/javascript">

    $(document).ready(function () {

        //to load templates to a hidden div
        $.get('/Templates/Templates.htm', function (data) {
            $('.hiddenData').html(data);
        });
    });

    $(window).scroll(function () {
        if ($(window).scrollTop() == $(document).height() - $(window).height()) {
            loadMore();
        }
    });
    var current = 0;
    var currentGoalPage = 0;
    function loadMore() {
        var sortBy = $('#sortby').val();
        var filterBy = $('#filterby').val();


        if (currentGoalPage > -1) {
            currentGoalPage++;

            $.ajax({
                url: "/Goal/GoalList",
                type: "POST",
                data: { sortBy: sortBy, filterBy: filterBy, page: currentGoalPage },
                dataType: "json",
                beforeSend: function () {
                    console.log("a");
                    $("#goalListContainer").find(".alert-info").remove();
                    $("#goalListContainer").append('<div class="alert alert-info" id="loadimage">Loading...</div>');
                },
                success: function (data) {
                    $('#loadimage').remove();
                    if (data.length != 0) {
                        loadTemplate(data);
                        $('#morelink').show();
                        if (data.length < 5) {
                            addNoMoreGoals();
                        }
                    } else {
                        addNoMoreGoals();
                    }
                }
            });

        }

        function addNoMoreGoals() {
            $('#morelink').hide();
            currentGoalPage = -1;
            $("#goalListContainer").find(".alert-info").remove();
            $("#goalListContainer").append('<div class="alert alert-info"> No more goals found </div>');
        }
    }

    function loadTemplate(data) {
        var source = $("#goalList-template").html();

        var template = Handlebars.compile(source);
        $("#goalListContainer").append(template({ objects: data }));
    }

    function ListOfGoals() {  
        var sortby = $("#sortby").val();
        var filterby = $("#filterby").val();
        var url = '/Goal/GoalList';
        $.get(url, { 'sortBy': sortby, 'filterBy': filterby, 'page': 0 }, function (result) {
            $("#goalListContainer").html('');
            if (result == '') {
                $("#goalListContainer").append('<div class="alert alert-info"> No goals found </div>');
                $('#morelink').hide();
            }
            else {
                $('#morelink').show();
            }
            currentGoalPage = 0;  
            loadTemplate(result);

        });

        //document.location.href="/Goal/GoalList?sortBy="+sortby+"&filterBy="+filterby;

    }
</script>

source/SocialGoal/Views/Goal/Reportpage.cshtml
@{
    ViewBag.Title = "Reportpage";
}

<div id="goalReport" class="well" style="padding-bottom:40px;">
</div>


<script type="text/javascript">
   
    $(document).ready(function () {
        LoadReport();
    });
   

    function LoadReport() {
        var goalId = $('#GoalId').val();
        var updates = $('#Updates').val();

        $.get("/Goal/GetGoalReport", { id: goalId }, function (result) {

            var data = [], target = [];
            $(result.Data).each(function (i, v) {
                data.push([v.Date, v.Value]);
            });
            $(result.Target).each(function (i, v) {
                target.push([v.EndDate, v.Target]);
            });
            if (data.length > 0) {
                setTimeout(drawChart(data, target), 10000);
            }

            if (data.length == 0) {
                $('#goalldetail').removeClass('well');
            }
            else {
                $('#goalldetail').addClass('well');
            }
        });
    }
</script>

source/SocialGoal/Views/Goal/SupportersOfUpdate.cshtml
@model SocialGoal.Web.ViewModels.UpdateSupportersViewModel

<div class="well">
@if (Model.Users.Count() == 0)
{
    <p class="span5 alert alert-info supporters-message">No Supporters</p>  
}
    @foreach (var item in Model.Users)
    {    
        <div style="margin:0px;padding:10px;">
         <div style="margin-left:1px;">
          
                <a href="@Url.Action("UserProfile", "Account", new { id = item.UserId }, null)" >
                    @Html.User().Avatar(item.ProfilePicUrl, new { @class = "span3", style = "margin-right:10px;" })
                </a>    
         </div>
         <div style="margin:0px;">  
            @Html.ActionLink(@item.UserName, "UserProfile", "Account", new { id = item.UserId }, null)
            <div>@item.Email</div>         
         </div>        
         </div>
               <hr />
              
            }
</div>



source/SocialGoal/Views/Goal/_CommentView.cshtml
@model IEnumerable<SocialGoal.Web.ViewModels.CommentsViewModel>

    @foreach (var item in Model)
    {
        <div class="span12" style="margin-left:1px;font-size:12px;">
            <div class ="span2">
                <a href="@Url.Action("UserProfile", "Account", new { id = item.UserId }, null)" >
                @Html.User().Avatar(item.User.ProfilePicUrl, new { @class = "span10" })
                </a>
            </div>
            <div class="span10" >              
                    <font color="green"> @Html.ActionLink(item.User.UserName, "UserProfile", "Account", new { id = item.UserId }, null) </font> commented "@item.CommentText"                    
                    <div>on @item.CommentDate</div>             
            </div>
        </div> 
        <hr />
    }


source/SocialGoal/Views/Goal/_DeleteUpdate.cshtml
@model SocialGoal.Model.Models.Update

@{
    ViewBag.Title = "_DeleteUpdate";
}

<div class="span12 alert alert-error fade in">
      
  <strong>Are you sure, you want to delete this update..?</strong>


    
    <table style="font-size:13px;font-weight:bold;">
        <tr >
            <td>Message :</td>
            <td>@Html.DisplayFor(model => model.Updatemsg)</td>
        </tr>
        <tr>
            <td>Status :</td>
            <td>  
                @Html.DisplayFor(model => model.status) 
                @if (Model.Goal.Metric != null && Model.Goal.Target != null)
                {
                    @Model.Goal.Metric.Type  @:/ @Model.Goal.Target @Model.Goal.Metric.Type 
                 }
            
            </td>
            
           
        </tr>
        
        
    </table>
   
    <div id="divDelete@(Model.UpdateId)">
    </div>
    @using (Html.BeginForm())
    {
        <p>
            <button class="btn btn-danger" type="submit" value="Submit">
                Delete</button>
                 <button class="btn" type="reset" value="Cancel" onclick="Cancel('@Model.GoalId')">
        Cancel</button>
        </p>
      
        
    }
   
</div>

source/SocialGoal/Views/Goal/_FollowedGoals.cshtml
@model IEnumerable<SocialGoal.Model.Models.Goal>
<div id="divSGoals" style="height: 150px;">
<div id="goals">
    @if (Model.Count() == 0)
    {
        <div class ="alert alert-info">No goals to display</div>
    }
    @foreach (var item in Model.Take(10))
    {
        <table class="table">
            <tr>
                <td class="span1">
                    <i class="icon-star"></i>
                </td>
                <td class="span9">
                    @Html.ActionLink(item.GoalName/*.LimitLength(30)*/, "Index", new { id = item.GoalId }, new { @title = item.GoalName })
                </td>
                <td class="span2">
                    <a id="UnSupport" href="#" onclick="UnSupportGoal(@item.GoalId)" style="float:right"><small>UnFollow</small>
                    </a>
                </td>
            </tr>
        </table>
			 
    }
    </div>
     </div>
   @if (Model.Count() > 10)
    { 
        @Html.ActionLink("See All", "GoalList", "Goal", new { filterBy = "My Followed Goals" }, new { @style = "float:right;" })
    }
   

source/SocialGoal/Views/Goal/_Goalslist.cshtml
@model IEnumerable<SocialGoal.Web.ViewModels.GoalListViewModel>
@{
    ViewBag.Title = "_Goalslist";
}


   
        @foreach (var item in Model)
        { <tr>
            <td class="span1">
                <i class="icon-star"></i>
            </td>
            <td class="span9">

                <div>@Html.ActionLink(item.GoalName, "Index", "Goal", new { id = item.GoalId }, null) </div>
                <div><small>@item.StartDate- @item.EndDate</small></div>
                <div><small> Created By @Html.ActionLink(item.UserName, "UserProfile", "Account", new { id = item.UserId }, null)on @item.CreatedDate</small></div>
            </td>
            <td class="span2"><strong>@item.SupportsCount</strong> Supporters
            </td>
        </tr>             
   
        }
           
   